#ifndef MESSAGE_H
#define MESSAGE_H
//========================================================================================================
//	FileName	:message.h
//	message tbl for handy terminal
//========================================================================================================


// error or warning message for BCR
static	char	*msg[]	=	{

	"DATA ERROR(Incorrect form)",  /*0*/
	"Master is not found       ",  /*1*/
	"                          ", /*2*/
	"                          ", /*3*/
	"                         ",  /*4*/
	"                          ", /*5*/
	"                          ", /*6*/
	"                         ",  /*7*/
	"                          ", /*8*/
	"                          ", /*9*/
/****Åè------------Åè------------Åè------------Åè------------*/
	"Job Not found			",  /*10*/
	"Curing Job Not found    ",  /*11*/
	"Metal Job Not found     ",  /*12*/
	"Rubber Job Not found     ", /*13*/
	"Spring Job Not found      ", /*14*/
	"Assmbly  Job Not found    ", /*15*/
	"Progress Order Not found  ", /*16*/
	"Progress Result Not found",  /*17*/
	"Label Job Not found       ", /*18*/
	"                          ", /*19*/
/****Åè------------Åè------------Åè------------Åè------------*/
	"Job Trn Master Not found ",  /*20*/
	"Cann't Insert FP Result   ",  /*21*/
	"JobClass Master Not found ", /*22*/ //2006.07.11
	"Cann't Insert PostCure  ", /*23*/
	"                         ",  /*24*/
	"                          ", /*25*/
	"                          ", /*26*/
	"                         ",  /*27*/
	"                          ", /*28*/
	"                          ", /*29*/
/****Åè------------Åè------------Åè------------Åè------------*/
	"All Process finished	   ",  /*30*/
	"Please Scan Take out First.",  /*31*/
	"Box have packing label    ", /*32*/
	"                          ", /*33*/
	"                         ",  /*34*/
	"                          ", /*35*/
	"                          ", /*36*/
	"                         ",  /*37*/
	"                          ", /*38*/
	"                          ", /*39*/
/****Åè------------Åè------------Åè------------Åè------------*/
/****Åè------------Åè------------Åè------------Åè------------*/
	"Cann't Insert Print Pack.",  /*40*/
	"Cann't Update Print Pack.",  /*41*/
	"Cann't Update Balance Rack", /*42*/
	"Cann't Insert PrintBox    ", /*43*/
	"Cann't Take In Balance   ",  /*44*/
	"Cann't Take Out Balance  ", /*45*/
	"Cann't Update print box  ", /*46*/
	"Cann't Update Fraction Rack",  /*47*/
	"Cann't Update Fraction", /*48*/
	"Cann't Update Lot        ", /*49 BPK3 */
/****Åè------------Åè------------Åè------------Åè------------*/
/****Åè------------Åè------------Åè------------Åè------------*/
	"All Process finished     ",  /*50*/
	"Please  Scan Curing Start",  /*51*/
	"Please  Scan PostCure first", /*52*/
	"Please  Scan Take Out first", /*53*/
	"Please  Scan Take Out     ",  /*54 BPL */
	"                          ", /*55*/
	"                          ", /*56*/
	"                         ",  /*57*/
	"                          ", /*58*/
	"                          ", /*59*/
/****Åè------------Åè------------Åè------------Åè------------*/
/****Åè------------Åè------------Åè------------Åè------------*/
	"Cann't Update Packing label",  /*60 BPL */
	"                         ",  /*61*/
	"                          ", /*62*/
	"                          ", /*63*/
	"                         ",  /*64*/
	"                          ", /*65*/
	"                          ", /*66*/
	"                         ",  /*67*/
	"                          ", /*68*/
	"                          ", /*69*/
/****Åè------------Åè------------Åè------------Åè------------*/
/****Åè------------Åè------------Åè------------Åè------------*/
	"                         ",  /*70*/
	"                         ",  /*71*/
	"                          ", /*72*/
	"                          ", /*73*/
	"                         ",  /*74*/
	"                          ", /*75*/
	"                          ", /*76*/
	"                         ",  /*77*/
	"                          ", /*78*/
	"                          ", /*79*/
/****Åè------------Åè------------Åè------------Åè------------*/
/****Åè------------Åè------------Åè------------Åè------------*/
	"Can't use this Rack no   ",  /*80*/
	"Same Item Code !!        ",  /*81*/
	"Fraction Label was used  ", /*82*/
	"                          ", /*83*/
	"                         ",  /*84*/
	"                          ", /*85*/
	"                          ", /*86*/
	"                         ",  /*87*/
	"                          ", /*88*/
	"                          ", /*89*/
/****Åè------------Åè------------Åè------------Åè------------*/
/****Åè------------Åè------------Åè------------Åè------------*/
	"Printer setting error!!  ",  /*90*/
	"Cann't Print Fraction     ",  /*91*/
	"Fraction Update Error    ", /*92*/
	"Fraction Not found       ", /*93*/
	"Rack Not found			  ",  /*94*/
	"Same Fraction Label!!    ", /*95*/
	"Fraction Insert Error    ", /*96*/
	"Cann't  RePrint box	  ",  /*97*/
	"Not MTCO Cann't Print    ", /*98*/
	"Fraction Label Not Found ", /*99*/
	"Double Box label         ",  /*100*/
/****Åè------------Åè------------Åè------------Åè------------*/
};
#endif
